# Generated by Django 4.0.1 on 2022-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bus_No', models.IntegerField()),
                ('Departure_Time', models.TimeField()),
                ('Destinations', models.CharField(max_length=1000)),
                ('Seats_Available', models.IntegerField()),
                ('TicketCosts', models.CharField(max_length=1000)),
            ],
        ),
    ]
